sudo: false
language: node_js
node_js:
  - 8
before_install: 
  - openssl aes-256-cbc -K $encrypted_8f2e1fe0e7f3_key -iv $encrypted_8f2e1fe0e7f3_iv -in ./config/secureConfig.js.enc -out ./config/secureConfig.js -d
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
before_script: sudo redis-server /etc/redis/redis.conf --requirepass  $redis_password
notifications:
  email:
    recipients:
    - jake1036@126.com
    on_success: always
    on_failure: always
script: 
  - npm test
after_success:
  - npm run test-cov
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master

after_deploy:
  - ssh $deploy_user@39.107.119.46 "pm2 restart datacenter"
addons:
  ssh_known_hosts: 39.107.119.46 # 请替换成自己的服务器IP
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken $COVERALLS_TOKEN   
